package org.habitbev.warehousemanagement.helpers.validators;

public enum WarehouseAction {

    SKU_BARCODE_GENERATION, INVENTORY_INBOUND, INVENTORY_OUTBOUND, ADD_INVENTORY, START_INBOUND, START_OUTBOUND, END_INBOUND, END_OUTBOUND, MOVE_INVENTORY;
}
